In [54]:
import pandas as pd
df = pd.read_csv(iris_csv_path)
df.columns = ['Id', 'SepalLength','SepalWidth','PetalLength','PetalWidth','Species']

print(df.head())
print(df.tail())

   Id  SepalLength  SepalWidth  PetalLength  PetalWidth      Species
0   1          5.1         3.5          1.4         0.2  Iris-setosa
1   2          4.9         3.0          1.4         0.2  Iris-setosa
2   3          4.7         3.2          1.3         0.2  Iris-setosa
3   4          4.6         3.1          1.5         0.2  Iris-setosa
4   5          5.0         3.6          1.4         0.2  Iris-setosa
      Id  SepalLength  SepalWidth  PetalLength  PetalWidth         Species
145  146          6.7         3.0          5.2         2.3  Iris-virginica
146  147          6.3         2.5          5.0         1.9  Iris-virginica
147  148          6.5         3.0          5.2         2.0  Iris-virginica
148  149          6.2         3.4          5.4         2.3  Iris-virginica
149  150          5.9         3.0          5.1         1.8  Iris-virginica

In [55]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           150 non-null    int64
 1   SepalLength  150 non-null    float64
 2   SepalWidth   150 non-null    float64
 3   PetalLength  150 non-null    float64
 4   PetalWidth   150 non-null    float64
 5   Species      150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None

In [56]:
df = pd.read_csv(iris_csv_path)
print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [57]:
df.columns = ['Id', 'SepalLength','SepalWidth','PetalLength','PetalWidth','Species']
df['sepal_sum'] = df['SepalLength'] + df['SepalWidth']
print("\nAfter adding new columns:")
display(df.head())

After adding new columns:

,Id,SepalLength,SepalWidth,PetalLength,PetalWidth,Species,sepal_sum
0,1,5.1,3.5,1.4,0.2,Iris-setosa,8.6
1,2,4.9,3.0,1.4,0.2,Iris-setosa,7.9
2,3,4.7,3.2,1.3,0.2,Iris-setosa,7.9
3,4,4.6,3.1,1.5,0.2,Iris-setosa,7.7
4,5,5.0,3.6,1.4,0.2,Iris-setosa,8.6

In [58]:
print("Description : ",df.describe())
print("Shape : ",df.shape)
print("Column names : ",df.columns)
print("Datatype of each col : ",df.dtypes)

Description :                 Id  SepalLength  SepalWidth  PetalLength  PetalWidth  \
count  150.000000   150.000000  150.000000   150.000000  150.000000
mean    75.500000     5.843333    3.054000     3.758667    1.198667
std     43.445368     0.828066    0.433594     1.764420    0.763161
min      1.000000     4.300000    2.000000     1.000000    0.100000
25%     38.250000     5.100000    2.800000     1.600000    0.300000
50%     75.500000     5.800000    3.000000     4.350000    1.300000
75%    112.750000     6.400000    3.300000     5.100000    1.800000
max    150.000000     7.900000    4.400000     6.900000    2.500000

        sepal_sum
count  150.000000
mean     8.897333
std      0.891718
min      6.800000
25%      8.300000
50%      8.850000
75%      9.575000
max     11.700000
Shape :  (150, 7)
Column names :  Index(['Id', 'SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth',
       'Species', 'sepal_sum'],
      dtype='object')
Datatype of each col :  Id               int64
SepalLength    float64
SepalWidth     float64
PetalLength    float64
PetalWidth     float64
Species         object
sepal_sum      float64
dtype: object

In [59]:
print(df['SepalLength'])

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLength, Length: 150, dtype: float64

In [60]:
print(df[['SepalLength','Species']])

     SepalLength         Species
0            5.1     Iris-setosa
1            4.9     Iris-setosa
2            4.7     Iris-setosa
3            4.6     Iris-setosa
4            5.0     Iris-setosa
..           ...             ...
145          6.7  Iris-virginica
146          6.3  Iris-virginica
147          6.5  Iris-virginica
148          6.2  Iris-virginica
149          5.9  Iris-virginica

[150 rows x 2 columns]

In [61]:
print(df.iloc[0],'\n')                     # returns first row
print(df.iloc[0:5],'\n')                   # returns first 5 rows
print(df.loc[0],'\n')                      # returns row by label
print(df.loc[:, 'SepalLength'],'\n')       # returns column by label

Id                       1
SepalLength            5.1
SepalWidth             3.5
PetalLength            1.4
PetalWidth             0.2
Species        Iris-setosa
sepal_sum              8.6
Name: 0, dtype: object

   Id  SepalLength  SepalWidth  PetalLength  PetalWidth      Species  \
0   1          5.1         3.5          1.4         0.2  Iris-setosa
1   2          4.9         3.0          1.4         0.2  Iris-setosa
2   3          4.7         3.2          1.3         0.2  Iris-setosa
3   4          4.6         3.1          1.5         0.2  Iris-setosa
4   5          5.0         3.6          1.4         0.2  Iris-setosa

   sepal_sum
0        8.6
1        7.9
2        7.9
3        7.7
4        8.6

Id                       1
SepalLength            5.1
SepalWidth             3.5
PetalLength            1.4
PetalWidth             0.2
Species        Iris-setosa
sepal_sum              8.6
Name: 0, dtype: object

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLength, Length: 150, dtype: float64

In [62]:
print(df[df['SepalLength'] > 5])

      Id  SepalLength  SepalWidth  PetalLength  PetalWidth         Species  \
0      1          5.1         3.5          1.4         0.2     Iris-setosa
5      6          5.4         3.9          1.7         0.4     Iris-setosa
10    11          5.4         3.7          1.5         0.2     Iris-setosa
14    15          5.8         4.0          1.2         0.2     Iris-setosa
15    16          5.7         4.4          1.5         0.4     Iris-setosa
..   ...          ...         ...          ...         ...             ...
145  146          6.7         3.0          5.2         2.3  Iris-virginica
146  147          6.3         2.5          5.0         1.9  Iris-virginica
147  148          6.5         3.0          5.2         2.0  Iris-virginica
148  149          6.2         3.4          5.4         2.3  Iris-virginica
149  150          5.9         3.0          5.1         1.8  Iris-virginica

     sepal_sum
0          8.6
5          9.3
10         9.1
14         9.8
15        10.1
..         ...
145        9.7
146        8.8
147        9.5
148        9.6
149        8.9

[118 rows x 7 columns]

In [63]:
df['SepalLength'] = pd.to_numeric(df['SepalLength']) # Convert to numeric
print(df[df['SepalLength'] > 5])

      Id  SepalLength  SepalWidth  PetalLength  PetalWidth         Species  \
0      1          5.1         3.5          1.4         0.2     Iris-setosa
5      6          5.4         3.9          1.7         0.4     Iris-setosa
10    11          5.4         3.7          1.5         0.2     Iris-setosa
14    15          5.8         4.0          1.2         0.2     Iris-setosa
15    16          5.7         4.4          1.5         0.4     Iris-setosa
..   ...          ...         ...          ...         ...             ...
145  146          6.7         3.0          5.2         2.3  Iris-virginica
146  147          6.3         2.5          5.0         1.9  Iris-virginica
147  148          6.5         3.0          5.2         2.0  Iris-virginica
148  149          6.2         3.4          5.4         2.3  Iris-virginica
149  150          5.9         3.0          5.1         1.8  Iris-virginica

     sepal_sum
0          8.6
5          9.3
10         9.1
14         9.8
15        10.1
..         ...
145        9.7
146        8.8
147        9.5
148        9.6
149        8.9

[118 rows x 7 columns]

In [64]:
print(df.sort_values('SepalLength', ascending=False).head(3))

      Id  SepalLength  SepalWidth  PetalLength  PetalWidth         Species  \
131  132          7.9         3.8          6.4         2.0  Iris-virginica
122  123          7.7         2.8          6.7         2.0  Iris-virginica
118  119          7.7         2.6          6.9         2.3  Iris-virginica

     sepal_sum
131       11.7
122       10.5
118       10.3

In [65]:
print(df.isnull())                   # Detect missing
print(df.isnull().sum())             # Count missing
df.dropna()                          # Drop missing
df.fillna(0)                         # Fill missing

        Id  SepalLength  SepalWidth  PetalLength  PetalWidth  Species  \
0    False        False       False        False       False    False
1    False        False       False        False       False    False
2    False        False       False        False       False    False
3    False        False       False        False       False    False
4    False        False       False        False       False    False
..     ...          ...         ...          ...         ...      ...
145  False        False       False        False       False    False
146  False        False       False        False       False    False
147  False        False       False        False       False    False
148  False        False       False        False       False    False
149  False        False       False        False       False    False

     sepal_sum
0        False
1        False
2        False
3        False
4        False
..         ...
145      False
146      False
147      False
148      False
149      False

[150 rows x 7 columns]
Id             0
SepalLength    0
SepalWidth     0
PetalLength    0
PetalWidth     0
Species        0
sepal_sum      0
dtype: int64

,Id,SepalLength,SepalWidth,PetalLength,PetalWidth,Species,sepal_sum
0,1,5.1,3.5,1.4,0.2,Iris-setosa,8.6
1,2,4.9,3.0,1.4,0.2,Iris-setosa,7.9
2,3,4.7,3.2,1.3,0.2,Iris-setosa,7.9
3,4,4.6,3.1,1.5,0.2,Iris-setosa,7.7
4,5,5.0,3.6,1.4,0.2,Iris-setosa,8.6
...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,9.7
146,147,6.3,2.5,5.0,1.9,Iris-virginica,8.8
147,148,6.5,3.0,5.2,2.0,Iris-virginica,9.5
148,149,6.2,3.4,5.4,2.3,Iris-virginica,9.6
149,150,5.9,3.0,5.1,1.8,Iris-virginica,8.9

In [66]:
print(df['SepalLength'].sum())
print(df['SepalLength'].mean())

876.5
5.843333333333334

In [67]:
print(df.groupby('Species').sum())

                   Id  SepalLength  SepalWidth  PetalLength  PetalWidth  \
Species
Iris-setosa      1275        250.3       170.9         73.2        12.2
Iris-versicolor  3775        296.8       138.5        213.0        66.3
Iris-virginica   6275        329.4       148.7        277.6       101.3

                 sepal_sum
Species
Iris-setosa          421.2
Iris-versicolor      435.3
Iris-virginica       478.1

In [68]:
print(df.groupby('Species')['SepalLength'].mean())

Species
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: SepalLength, dtype: float64

In [70]:
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target
print(df.head())
print(df.columns)

df['sepal_sum'] = df['sepal length (cm)'] + df['sepal width (cm)']
df['species_name'] = df['target'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})
print(df.head())
print(df.columns)

columns_to_remove = ['sepal width (cm)', 'sepal_sum']
columns_to_remove = [col for col in columns_to_remove if col in df.columns]
df = df.drop(columns=columns_to_remove, axis=1)
print(df.head())
print(df.columns)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   target
0       0
1       0
2       0
3       0
4       0
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   target  sepal_sum species_name
0       0        8.6       setosa
1       0        7.9       setosa
2       0        7.9       setosa
3       0        7.7       setosa
4       0        8.6       setosa
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target', 'sepal_sum', 'species_name'],
      dtype='object')
   sepal length (cm)  petal length (cm)  petal width (cm)  target species_name
0                5.1                1.4               0.2       0       setosa
1                4.9                1.4               0.2       0       setosa
2                4.7                1.3               0.2       0       setosa
3                4.6                1.5               0.2       0       setosa
4                5.0                1.4               0.2       0       setosa
Index(['sepal length (cm)', 'petal length (cm)', 'petal width (cm)', 'target',
       'species_name'],
      dtype='object')

In [71]:
df.isnull().sum()

sepal length (cm)    0
petal length (cm)    0
petal width (cm)     0
target               0
species_name         0
dtype: int64

In [72]:
df.isnull().sum().sum()

np.int64(0)

In [73]:
df.isnull().values.any()

np.False_